name: Tests

on:
  push:
    branches-ignore:
      - dependabot/*
  pull_request:
    branches:
      - master

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run clippy action to produce annotations
        # Don't run on dependabot PRs
        # https://github.com/actions-rs/clippy-check/issues/2#issuecomment-807852653
        if: github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]'
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
      - name: Run clippy manually without annotations
        if: github.event.pull_request.head.repo.full_name != github.repository || github.actor == 'dependabot[bot]'
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets -- -D warnings
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/cargo@v1
        with:
          command: test
